hw2 done
aHadoouken/afina pull request #2
Opened 2022-03-07 20:11 UTC by aHadoouken

2022-03-08 11:50 UTC, xphoenix commented on src/network/mt_blocking/ServerImpl.cpp
> +        while (!thread_pool.empty()) {
- Был 1 клиент
- Один поток ждал в join
- Клиент ушел
- Поток ушел из join
- Сервер продолжает работать

2022-03-08 11:51 UTC, xphoenix commented on src/network/mt_blocking/ServerImpl.cpp
> +        cv.notify_all();
Зачем уведомлять всех, когда выходит очередной поток? Ждет join, причем условия _все потоки вышли_

2022-03-08 11:52 UTC, xphoenix commented on src/network/mt_blocking/ServerImpl.h
> +    std::map<std::thread::id, int> thread_pool;
Это _не thread pool_, название не то

2022-03-08 11:54 UTC, xphoenix commented on src/network/mt_blocking/ServerImpl.cpp
>      close(_server_socket);
- Ресурсы нужно освобождать на _владеющем_ потоке (close)
- Зачем использовать _thread.join_ если у тебя уже есть conditional_variable
- Что будет с assert(_thread.joinable()) если поток _уже_ остановился?

2022-03-10 12:18 UTC, xphoenix commented on src/network/mt_blocking/ServerImpl.cpp
> +                client_thr.detach();
Нарушение лимитов

2022-03-15 18:09 UTC, Fen99 requested changes
~ServerImpl() = Stop() + Join()

2022-03-15 18:09 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +        char client_buffer[4096];
= ""; //!

2022-03-15 18:09 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
>      std::size_t arg_remains;
= 0;

2022-03-15 18:09 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +                        break;
Здесь мы теряем текущее содержимое буфера при следующем чтении

2022-03-16 21:47 UTC, Fen99 approved these changes

2022-03-17 18:54 UTC, merged